In [17]:
import pandas as pd

# Charger le dataset
df = pd.read_csv('Clean_Dataset.csv')
df

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955
...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300153 entries, 0 to 300152
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0        300153 non-null  int64
 1   airline           300153 non-null  object
 2   flight            300153 non-null  object
 3   source_city       300153 non-null  object
 4   departure_time    300153 non-null  object
 5   stops             300153 non-null  object
 6   arrival_time      300153 non-null  object
 7   destination_city  300153 non-null  object
 8   class             300153 non-null  object
 9   duration          300153 non-null  float64
 10  days_left         300153 non-null  int64
 11  price             300153 non-null  int64
dtypes: float64(1), int64(3), object(8)
memory usage: 27.5+ MB

In [19]:
df.shape

(300153, 12)

In [20]:
df.isna().sum()

Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [21]:
df.describe()

          Unnamed: 0       duration      days_left          price
count  300153.000000  300153.000000  300153.000000  300153.000000
mean   150076.000000      12.221021      26.004751   20889.660523
std     86646.852011       7.191997      13.561004   22697.767366
min         0.000000       0.830000       1.000000    1105.000000
25%     75038.000000       6.830000      15.000000    4783.000000
50%    150076.000000      11.250000      26.000000    7425.000000
75%    225114.000000      16.170000      38.000000   42521.000000
max    300152.000000      49.830000      49.000000  123071.000000

In [24]:
df["class"].value_counts()

class
Economy     206666
Business     93487
Name: count, dtype: int64

Analyse descriptive de tes 300 153 réservations révèle un marché du billet d'avion extrêmement polarisé, où la moyenne de 20 889 est fortement distordue par des valeurs extrêmes. Le fait que la médiane (7 425) soit trois fois inférieure à la moyenne indique une asymétrie positive majeure : la grande majorité des passagers voyage à bas prix, tandis qu'une minorité (le dernier quart des données commençant à 42 521) paie des tarifs premium pouvant atteindre 123 071. Cette dispersion massive, confirmée par un écart-type très élevé de 22 697, montre que des facteurs comme la classe (Business vs Economy) et l'anticipation de l'achat (entre 1 et 49 jours) ne sont pas de simples variables, mais les véritables moteurs qui fragmentent ton dataset en deux segments de clientèle totalement distincts.

Persona :

On distingue deux profils types : d'un côté, l'Explorateur Économe, qui représente la masse des données, réserve presque deux mois à l'avance (49 jours) et voyage en classe Economy pour minimiser ses coûts. De l'autre, le Professionnel Pressé, qui appartient au dernier quart du dataset (les prix au-dessus de 42 521), réserve dans l'urgence (1 à 7 jours avant) et privilégie la classe Business peu importe le tarif. Cette distinction est cruciale car elle montre que le prix final dépend moins de la distance parcourue que du profil du passager et de son besoin de flexibilité ou de confort